apiVersion: v1
kind: Service
metadata:
  name: genieacs-mongo
  labels:
    app: genieacs
spec:
  ports:
    - port: 27017
  selector:
    app: genieacs
    tier: mongo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    app: genieacs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: genieacs-mongo
  labels:
    app: genieacs
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: genieacs
        tier: mongo
    spec:
      containers:
      - image: bitnami/mongodb:latest
        name: mongo
        env:
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /var/lib/mongo
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
